Created new note UI and fixed form validation
gaagul/neeto-ui-challenge pull request #11
Opened 2022-09-23 11:54 UTC by gaagul

Fixes #5 

Made changes according to the reviews.

2022-09-23 13:45 UTC, yedhink requested changes
@gaagul

2022-09-23 13:45 UTC, yedhink commented on app/javascript/src/components/Dashboard/Notes/DeleteAlert.jsx
> +    message={`Are you sure you want to delete the ${selectedNote} ? This action cannot be undone.`}
```suggestion
    message={`Are you sure you want to delete the note, "${selectedNote}"? This action cannot be undone.`}
```

2022-09-23 13:45 UTC, yedhink commented on app/javascript/src/components/Dashboard/Notes/Pane/CreateNotePane.jsx
> +const CreateNotePane = ({ showPane, setShowPane }) => {
https://academy.bigbinary.com/learn-react/pages/structuring-code#:~:text=Avoid%20Unnecessary%20Namespacing

2022-09-23 13:45 UTC, yedhink commented on app/javascript/src/components/Dashboard/Notes/Pane/Form.jsx
> +              placeholder="Select tag"
```suggestion
              placeholder="Select tags"
```

2022-09-23 13:45 UTC, yedhink commented on app/javascript/src/components/Dashboard/Notes/constants.js
> +];
Build these select options rather than hardcoding.

2022-09-23 18:49 UTC, merged

2022-09-23 19:22 UTC, gaagul commented on app/javascript/src/components/Dashboard/Notes/constants.js
> +];
I did not understand what you meant by building the select options,
I made this constant since this is the format the Select component accepts in the options attribute,
I am not able to find out what I am doing wrong here, can you please point it out to me?

2022-09-24 08:42 UTC, yedhink commented on app/javascript/src/components/Dashboard/Notes/constants.js
> +];
@gaagul https://bigbinary.slack.com/archives/C01T5Q4DZAR/p1663335627615309?thread_ts=1663060378.971029&cid=C01T5Q4DZAR

2022-09-25 05:44 UTC, gaagul commented on app/javascript/src/components/Dashboard/Notes/constants.js
> +];
Thank you for pointing it out to me.
I will make sure that necessary changes will be made to the code and I will keep this in mind for the future also.