Created note listing page UI
gaagul/neeto-ui-challenge pull request #9
Opened 2022-09-22 07:42 UTC by gaagul

Fixes #3

2022-09-22 08:05 UTC, yedhink requested changes
@gaagul

2022-09-22 08:05 UTC, yedhink commented on app/javascript/src/components/Dashboard/Notes/Menu.jsx
> +// @ts-ignore
Be careful now. I had put up a lot of review comments in the Slack thread. The point of adding them in that thread is to ensure that I don't have to again provide redundant review comments. Go through the thread very well and make necessary changes where ever required.

2022-09-22 08:05 UTC, yedhink commented on app/javascript/src/components/Dashboard/Notes/NoteCard.jsx
> +        <li onClick={setShowDeleteAlert}>Delete</li>
Go through the Slack thread.

2022-09-22 08:05 UTC, yedhink commented on app/javascript/src/components/Dashboard/Notes/NoteCard.jsx
> +    <div>
Why do we need this div?

2022-09-22 08:05 UTC, yedhink commented on app/javascript/src/components/Dashboard/Notes/NoteCard.jsx
> +            {`Created ${dayjs(createdAt).fromNow()}`}
Move these into utils.

2022-09-22 08:05 UTC, yedhink commented on app/javascript/src/components/Dashboard/Notes/NoteCard.jsx
> +            name: "neeto UI",
```suggestion
            name: "neetoUI",
```

2022-09-22 08:05 UTC, yedhink commented on app/javascript/src/components/Dashboard/Notes/index.jsx
> +          menuBarToggle={() => setShowMenuBar(!showMenuBar)}
https://academy.bigbinary.com/learn-react/pages/know-when-to-use-previous-state-for-state-update

2022-09-22 08:05 UTC, yedhink commented on app/javascript/src/components/Dashboard/Notes/index.jsx
> +              description={note["description"]}
Use `dot` notation.

2022-09-22 08:05 UTC, yedhink commented on app/javascript/src/components/Dashboard/Notes/index.jsx
> +            setSelectedNoteIds={[]}
Why is this passed with an empty array when the value is supposed to be a function?

2022-09-22 08:05 UTC, yedhink commented on app/javascript/src/utils/dayjs.js
> +export default dayjs;
https://academy.bigbinary.com/learn-react/pages/miscellaneous-tips#:~:text=How%20to%20extend%20day.js%3F

2022-09-22 12:23 UTC, gaagul commented on app/javascript/src/components/Dashboard/Notes/index.jsx
> +            setSelectedNoteIds={[]}
Sorry for leaving it like that, I was hoping to deal with the whole delete section while Solving issue 4.
I will make sure that these mistakes won't happen from now on.

2022-09-22 17:48 UTC, merged

2022-09-22 18:08 UTC, gaagul commented on app/javascript/src/components/Dashboard/Notes/NoteCard.jsx
> +        <li onClick={setShowDeleteAlert}>Delete</li>
` const handleDelete = () => {
    setShowDeleteAlert(true);
    setSelectedNote(note);
  };`
.
.
.
.
` <li onClick={handleDelete}>Delete</li> `

I have created a handledelete function inside NotesCard component and passed it in the onClick attribute,
Is this the correct way to solve the above-mentioned problem in the code?

2022-09-23 08:21 UTC, yedhink commented on app/javascript/src/components/Dashboard/Notes/NoteCard.jsx
> +        <li onClick={setShowDeleteAlert}>Delete</li>
Don't think you've gone very well through the Slack thread. https://bigbinary.slack.com/archives/C01T5Q4DZAR/p1663761829787419?thread_ts=1663060378.971029&cid=C01T5Q4DZAR

2022-09-23 09:19 UTC, gaagul commented on app/javascript/src/components/Dashboard/Notes/NoteCard.jsx
> +        <li onClick={setShowDeleteAlert}>Delete</li>
Sorry for that silly mistake from my side,
I have changed the list to MenuItem.Button and also went through the Semantic HTML and accessibility part in the handbook once again to make sure that I understood it perfectly.